### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by madshadsen** [tvarit-foggy/grafana-s3-plugin#6]
I'm interested in trying this out, but I was unable to figure out how I would install it. Can you provide a link or similar?

I'm using Grafana cloud starter edition.

**Comment by nikoe14** [comment]
It would be nice to have clear instructions about how to do it.

Thanks!

**Comment by KamalGalrani** [comment]
Thanks for pointing out. I have included this in README.md

https://github.com/tvarit-foggy/grafana-s3-plugin/blob/master/README.md
