### ISSUE TITLE
when i try to run query from plugin, it gives me nosuchkey error

### ISSUE THREAD

**Issue by vivekcts** [tvarit-foggy/grafana-s3-plugin#9]
The error : - NoSuchKey: The specified key does not exist. status code: 404, request id: E5AE50E2543C37CE, host id: mfcQYp9T1icc0AaF74jycp1mEua9DCT1qWdcH8MFThOFk4B6lCEogqg1m0zquD0rZkfeVPt8JuE=

However when added S3 as datasource i can see in s3 explorer in plugins all the files in s3 bucket. but when i query them it give me nosuchkey error as shown above.

can you pls share any screenshot where plugin has successfully queried a csv file from the plugin. just that i need to see what all options i want to fill

first option is "path" , not sure what to fill tried many options their.

![image](https://user-images.githubusercontent.com/23396101/91484821-6f8a3880-e8dc-11ea-8f45-f189595c84bf.png)

**Comment by KamalGalrani** [comment]
Path should not start with s3://<bucket_name>/. It should just be the key of the file
Wildcard paths are not supported yet. Though they are planned for near future
